''
'' The groot theme
'' some colors borrowed from the superhero theme
'' https://bootswatch.com/superhero/
'' author: Jonathan Baldwin

'' Superhero 5.1.0
'' Bootswatch

'' $theme: "superhero"

!startsub colorSystem
  ''
  '' Color system
  ''

  !$white    = "#ffffff"
  !$gray_100 = "#ebebeb"
  !$gray_200 = "#4e5d6c"
  !$gray_300 = "#dee2e6"
  !$gray_400 = "#ced4da"
  !$gray_500 = "#adb5bd"
  !$gray_600 = "#868e96"
  !$gray_700 = "#495057"
  !$gray_800 = "#343a40"
  !$gray_900 = "#212529"
  !$black    = "#000000"

  '' https://coolors.co/4c9be8-6610f2-6f42c1-e83e8c-d9534f-f0ad4e-ffc107-5cb85c-20c997-5bc0de
  !$blue =    "#4c9be8"
  !$indigo =  "#6610f2"
  !$purple =  "#6f42c1"
  !$pink =    "#e83e8c"
  !$red =     "#d9534f"
  !$orange =  "#f0ad4e"
  !$yellow =  "#ffc107"
  !$green =   "#5cb85c"
  !$teal =    "#20c997"
  !$cyan =    "#5bc0de"

  !$primary =       $blue
  !$secondary =     $gray_200
  !$success =       $green
  !$info =          $cyan
  !$warning =       $yellow
  !$danger =        $red
  !$light =         %lighten($gray_200, 35)
  !$dark =          "#20374c"

  !$tint = 40
  !function $darken($color, $amount=$tint)
    !return %darken($color, $amount)
  !endfunction

  !function $lighten($color, $amount=$tint)
    !return %lighten($color, $amount)
  !endfunction

  !$fgcolor = $white
  !$bgcolor = $gray_300

  !$primary_dark = $darken($primary, $tint)
  !$primary_light = $lighten($primary, $tint)
  !$primary_text = $white

  !$secondary_dark = $darken($secondary, $tint)
  !$secondary_light = $lighten($secondary, $tint)
  !$secondary_text = $white

  !$info_dark = $darken($info)
  !$info_light = $lighten($info)
  !$info_text = $white

  !$success_dark = $darken($success)
  !$success_light = $lighten($success)
  !$success_text = $white

  !$warning_dark = $darken($warning)
  !$warning_light = $lighten($warning)
  !$warning_text = $white

  !$danger_dark = $darken($danger)
  !$danger_light = $lighten($danger)
  !$danger_text = $white

!endsub


' ====== Default Colors ======
!startsub Defaults
  ''
  '' Global Default Values
  ''
  skinparam dpi                     92
  skinparam shadowing               false
  skinparam roundcorner             7
  skinparam ParticipantPadding      10
  skinparam BoxPadding              20
  skinparam Padding                 5
  skinparam ArrowColor              $dark

  skinparam stereotype {
      CBackgroundColor              $secondary_light
      CBorderColor                  $secondary_dark
      ABackgroundColor              $success_light
      ABorderColor                  $success_dark
      IBackgroundColor              $danger_light
      IBorderColor                  $danger_dark
      EBackgroundColor              $warning_light
      EBorderColor                  $warning_dark
      NBackgroundColor              $info_light
      NBorderColor                  $info_dark
  }

  skinparam legend {
    BackgroundColor                 $secondary
    BorderColor                     $secondary_dark
    FontColor                       $white
  }

  !procedure $primary_scheme()
    FontColor $primary_text
    BorderColor $primary_dark
    BackgroundColor $primary
  !endprocedure
!endsub

!startsub sequence
   skinparam sequence {
    ''
    BoxBackgroundColor              $bgcolor
    BoxBorderColor                  $dark
    BoxFontColor                    $dark
    
    ''
    LifeLineBorderColor             $secondary
    LifeLineBorderThickness         2
    LifeLineBackgroundColor         $secondary_dark
    ''
    GroupBackgroundColor            $secondary
    GroupBorderColor                $dark
    GroupFontColor                  $dark
    GroupHeaderFontColor            $info
    GroupHeaderBackgroundColor      $bgcolor
    GroupBodyBackgroundColor        $white
    GroupBorderThickness            1
    ''  
    DividerBackgroundColor          $dark
    DividerBorderColor              $dark
    DividerBorderThickness          2
    DividerFontColor                $light
    ''  
    ReferenceBackgroundColor        $bgcolor
    ReferenceBorderColor            $dark
    ReferenceFontColor              $dark
    ReferenceHeaderFontColor        $info
    ReferenceHeaderBackgroundColor  $secondary
  }

!endsub

!startsub participant 
  skinparam participant {
    $primary_scheme()
  }
!endsub


' ====== HTTP ======
!startsub HTTP
  ' swagger colors
  ' https://coolors.co/61affe-49cc90-fca130-50e3c2-f93e3e

  !$rest = {
    "get"     :   "#61affe",
    "post"    :   "#49cc90",
    "put"     :   "#fca130",
    "patch"   :   "#50e3c2",
    "delete"  :   "#f93e3e"
  }

  !procedure $http($verb, $endpoint, $body="")
    !$isPost = %lower($verb) == 'post'
    !$isPut = %lower($verb) == 'put'
    !$isPatch = %lower($verb) == 'patch'
    !$isDelete = %lower($verb) == 'delete'
    !$isGet = %lower($verb) == 'get'
    !if ($isPost)
      $post($endpoint, $body)
    !elseif ($isPut)
      $put($endpoint)
    !elseif ($isPatch)
      $patch($endpoint)
    !elseif ($isDelete)
      $delete($endpoint)
    !else
      $get($endpoint)
    !endif
  !endprocedure

  !function $get($endpoint)
    !return "<font color=" + $rest.get + ">**GET** <font color=black>" + $endpoint
  !endfunction

  !function $post($endpoint, $body)
    !return "<font color=" + $rest.post + ">**POST** <font color=black>" + $endpoint
  !endfunction

  !function $put($endpoint)
    !return "<font color=" + $rest.put + ">**PUT** <font color=black>" + $endpoint
  !endfunction

  !function $patch($endpoint)
    !return "<font color=" + $rest.patch + ">**PATCH** <font color=black>" + $endpoint
  !endfunction

  !function $delete($endpoint)
    !return "<font color=" + $rest.delete + ">**DELETE** <font color=black>" + $endpoint
  !endfunction
!endsub

' =======  Angular =======
' Component, Template, Directive, Pipe, Authguard, Service, Module
!startsub Angular

  ' https://coolors.co/e53935-0288d1-ab47bc-43a047-00897b-43a047-ffca28-e44d26

  !$ng = {
    "component" :   "#ffffff",
    "default"   :   "#e53935",
    "directive" :   "#ab47bc",
    "guard"     :   "#43a047",
    "pipe"      :   "#00897b",
    "resolver"  :   "#43a047",
    "service"   :   "#ffca28",
    "template"  :   "#e44d26",
    "module"    :   "#e53935",
    "text"      :   "#000000"
  }

  !procedure $initSterotype($type, $color)
    BackgroundColor<<$type>> $color
    BorderColor<<$type>> %darken($color, 50)
      FontColor $black
  !endprocedure

  skinparam component {
      $initSterotype("Component", $ng.component)
      $initSterotype("Directive", $ng.directive)
      $initSterotype("Guard", $ng.guard)
      $initSterotype("Module", $ng.module)
      $initSterotype("Pipe", $ng.pipe)
      $initSterotype("Resolver", $ng.resolver)
      $initSterotype("Service", $ng.service)
      $initSterotype("Template", $ng.template)
  }

  skinparam participant {
      $initSterotype("Component", $ng.component)
      $initSterotype("Directive", $ng.directive)
      $initSterotype("Guard", $ng.guard)
      $initSterotype("Module", $ng.module)
      $initSterotype("Pipe", $ng.pipe)
      $initSterotype("Resolver", $ng.resolver)
      $initSterotype("Service", $ng.service)
      $initSterotype("Template", $ng.template)
  }
!endsub


